---
- name: Creating Webapps Group
  group: name={{ appgroup }} system=yes state=present

- name: Creating Webapps Directory
  file: path={{ appsrc }} state=directory 

- name: Creating scwebapp System Account
  user: name={{ appname }} system=yes group={{ appgroup }} shell=/bin/bash home={{ appbase }}

- name: Creating scwebapp Postgres Role
  sudo: True
  sudo_user: postgres
  postgresql_user: name={{ pguser }} password={{ pgpass }} role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE state=present

- name: Creating scwebapp Postgres DB
  sudo: True
  sudo_user: postgres
  postgresql_db: name={{ pgname }} owner={{ pguser }}

- name: Settings scwebapp DB Privileges
  sudo: True
  sudo_user: postgres
  postgresql_privs: db={{ pgname }} privs=ALL type=database roles={{ pguser }}

- name: Adding the scwebapp environment vars
  template: src=bash_profile.j2 dest={{ appbase }}/.bash_profile owner={{ appname }} group={{ appgroup }} mode=0777

- name: Creating Project Directory
  file: path={{ appbase }} state=directory owner={{ appname }}

- name: Cloning SCWebApp Github Repo
  git: repo={{ githubrepo }} dest={{ approot }} accept_hostkey=yes key_file={{ githubkey }}

- name: Creating Virtual Environment
  pip: virtualenv={{ appbase }} state=present requirements={{ approot }}/requirements.txt

- name: Copying uWSGI site config files
  template: src=scwebapp.ini.j2 dest={{ uwsgisites }}/scwebapp.ini

- name: Copying DB Migration Scripts
  template: src=migrate.sh.j2 dest={{ appbase }}/migrate.sh owner={{ appname }} group={{ appgroup }} mode=0777

- name: Running Migrate and Collectstatic
  command: ./migrate.sh chdir={{ appbase }}

- name: Cleaning up temp files
  file: path={{ appbase }}/migrate.sh state=absent

- name: Setting Application Ownership
  file: path={{ appbase }} owner={{ appname }} group={{ appgroup }} recurse=yes state=directory
